# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Trigger')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('image', models.ImageField(upload_to='courses/image', verbose_name='Image')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create in ')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Update in ')),
            ],
        ),
    ]
