# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171119_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update in '),
        ),
    ]
