# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180215_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='announcements',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
