# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date avaliable'),
        ),
    ]
